### ISSUE TITLE
char-rnn errors prob_dist must be 1 or 2 dim (multinomial_out at ../aten/src/ATen/native/Distributions.cpp:418)

### ISSUE THREAD

**Issue by sbeckeriv** [LaurentMazare/tch-rs#207]
Dearest Maintainer,

I am running Ubuntu 20 if it matters.  I just got cuda working and I am a little lost. I was using these examples to test it. Any thoughts or suggestions are appreciated.  I am using the suggested data file from the example docs. 

```
 cargo run --example char-rnn
```
Here is the 

```
usage. To compact weights again call flatten_parameters(). (_cudnn_impl at ../aten/src/ATen/native/cudnn/RNN.cpp:1269)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("prob_dist must be 1 or 2 dim (multinomial_out at ../aten/src/ATen/native/Distributions.cpp:418)\nframe #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fe26e009aaa in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libc10.so)\nframe #1: at::native::multinomial_out(at::Tensor&, at::Tensor const&, long, bool, at::Generator*) + 0x607 (0x7fe26ee5a117 in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libtorch_cpu.so)\nframe #2: at::native::multinomial(at::Tensor const&, long, bool, at::Generator*) + 0x92 (0x7fe26ee63642 in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libtorch_cpu.so)\nframe #3: <unknown function> + 0x396d9fc (0x7fe280db69fc in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libtorch_cuda.so)\nframe #4: <unknown function> + 0x39a79fe (0x7fe280df09fe in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libtorch_cuda.so)\nframe #5: <unknown function> + 0x2bf63d7 (0x7fe270e213d7 in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libtorch_cpu.so)\nframe #6: <unknown function> + 0x39a79fe (0x7fe280df09fe in /home/becker/Downloads/libtorch-cxx11-abi-shared-with-deps-1.5.0+cu101/libtorch/lib/libtorch_cuda.so)\nframe #7: <unknown function> + 0xa7b13 (0x562ec558cb13 in target/debug/examples/char-rnn)\nframe #8: <unknown function> + 0x9c385 (0x562ec5581385 in target/debug/examples/char-rnn)\nframe #9: <unknown function> + 0x93414 (0x562ec5578414 in target/debug/examples/char-rnn)\nframe #10: <unknown function> + 0x8a5b4 (0x562ec556f5b4 in target/debug/examples/char-rnn)\nframe #11: <unknown function> + 0x7c3f2 (0x562ec55613f2 in target/debug/examples/char-rnn)\nframe #12: <unknown function> + 0x824d2 (0x562ec55674d2 in target/debug/examples/char-rnn)\nframe #13: <unknown function> + 0x50290 (0x562ec5535290 in target/debug/examples/char-rnn)\nframe #14: <unknown function> + 0x52275 (0x562ec5537275 in target/debug/examples/char-rnn)\nframe #15: <unknown function> + 0x243da (0x562ec55093da in target/debug/examples/char-rnn)\nframe #16: <unknown function> + 0x25356 (0x562ec550a356 in target/debug/examples/char-rnn)\nframe #17: <unknown function> + 0x286db (0x562ec550d6db in target/debug/examples/char-rnn)\nframe #18: <unknown function> + 0xd8a79 (0x562ec55bda79 in target/debug/examples/char-rnn)\nframe #19: <unknown function> + 0x286b7 (0x562ec550d6b7 in target/debug/examples/char-rnn)\nframe #20: <unknown function> + 0x2587a (0x562ec550a87a in target/debug/examples/char-rnn)\nframe #21: __libc_start_main + 0xf3 (0x7fe26dd880b3 in /lib/x86_64-linux-gnu/libc.so.6)\nframe #22: <unknown function> + 0x2392e (0x562ec550892e in target/debug/examples/char-rnn)\n")', src/wrappers/tensor_generated.rs:5390:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  11: rust_begin_unwind
             at src/libstd/panicking.rs:385
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:89
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  14: core::result::Result<T,E>::unwrap
             at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15: tch::wrappers::tensor_generated::<impl tch::wrappers::tensor::Tensor>::multinomial
             at src/wrappers/tensor_generated.rs:5390
  16: char_rnn::sample
             at examples/char-rnn/main.rs:30
  17: char_rnn::main
             at examples/char-rnn/main.rs:65
  18: std::rt::lang_start::{{closure}}
             at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  21: std::panicking::try
             at src/libstd/panicking.rs:274
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /home/becker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  25: main
  26: __libc_start_main
  27: _start
```

I get this warning a lot as well. 
```
Warning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (_cudnn_impl at ../aten/src/ATen/native/cudnn/RNN.cpp:1269)
```

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, I just pushed a fix that should get rid of the problem. It should above remove the very verbose warnings by optimizing the weights layout as suggested in the message.

**Comment by sbeckeriv** [comment]
thanks!
