### ISSUE TITLE
Hunt SIGBUS from Tensor::drop

### ISSUE THREAD

**Issue by jerry73204** [LaurentMazare/tch-rs#253]
This is a weird bug I still cannot tell the reasons. The program runs in a forward backward loop and gets killed by SIGBUS in less than five minutes (sometimes immediately). It's only happens on specific machine. I opened rust-gdb to catch the SIGBUS and it says SIGBUS raised from `Tensor::drop`, and the line number points to the end of a function. I would bet it's somewhat a CUDA memory error, but gather further information. Let me paste the details and to see if anyhow has thoughts.

- OS: CentOS 7
- CPU: Intel Xeon Processor (Skylake)
- GPU: Tesla P100-PCIE-16GB
- Python 3.6 and PyTorch 1.6.0 installed by `pip3 install --user`
- CUDA 10.2 and CUDNN 7

GDB points the error happens [here](https://github.com/jerry73204/yolo-dl/blob/9844b9ac49a5f740018696d45e30f910c14dbddd/src/train/main.rs#L134).

The GDB backtrace.

```
#0  0x00007fffab4b1cf0 in c10::cuda::CUDACachingAllocator::DeviceCachingAllocator::free_block(c10::cuda::CUDACachingAllocator::(anonymous namespace)::Block*) ()
   from /home/centos/.local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so
#1  0x00007fffab4b38bb in c10::cuda::CUDACachingAllocator::raw_delete(void*) () from /home/centos/.local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so
#2  0x00007fffac8b59cd in c10::TensorImpl::release_resources() () from /home/centos/.local/lib/python3.6/site-packages/torch/lib/libc10.so
#3  0x000055555583bbdb in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::reset_ (this=0x7ffbf5313280) at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/atomicity.h:69
#4  c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::~intrusive_ptr (this=0x7ffbf5313280, __in_chrg=<optimized out>)
    at /home/centos/.local/lib/python3.6/site-packages/torch/include/c10/util/intrusive_ptr.h:249
#5  at::Tensor::~Tensor (this=0x7ffbf5313280, __in_chrg=<optimized out>) at /home/centos/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:86
#6  torch::autograd::AutogradMeta::~AutogradMeta (this=0x7ffbf5313270, __in_chrg=<optimized out>)
    at /home/centos/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/variable.h:189
#7  torch::autograd::AutogradMeta::~AutogradMeta (this=0x7ffbf5313270, __in_chrg=<optimized out>)
    at /home/centos/.local/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/variable.h:189
#8  0x00007fffac8b59a0 in c10::TensorImpl::release_resources() () from /home/centos/.local/lib/python3.6/site-packages/torch/lib/libc10.so
#9  0x000055555584400a in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::reset_ (this=0x7ffbf5313330) at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/atomic_base.h:326
#10 0x00005555558440d7 in c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::~intrusive_ptr (this=0x7ffbf5313330, __in_chrg=<optimized out>)
    at /home/centos/.local/lib/python3.6/site-packages/torch/include/c10/util/intrusive_ptr.h:248
#11 at::Tensor::~Tensor (this=0x7ffbf5313330, __in_chrg=<optimized out>) at /home/centos/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:86
#12 at_free (t=0x7ffbf5313330) at libtch/torch_api.cpp:374
#13 0x000055555582bcbe in <tch::wrappers::tensor::Tensor as core::ops::drop::Drop>::drop (self=<optimized out>)
    at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/tch-0.2.0/src/wrappers/tensor.rs:470
#14 0x000055555571dd0f in core::ptr::drop_in_place () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
#15 core::ptr::drop_in_place () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
#16 <alloc::vec::Vec<T> as core::ops::drop::Drop>::drop (self=0x7fff4d7ed5a0)
    at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2637
#17 core::ptr::drop_in_place () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
#18 core::ptr::drop_in_place () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
#19 core::ptr::drop_in_place () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
#20 core::ptr::drop_in_place () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
#21 alloc::sync::Arc<T>::drop_slow (self=0x7fffa837d2d8) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:934
#22 0x00005555556432cc in train::train_worker (config=..., input_channels=<optimized out>, num_classes=<optimized out>, training_rx=...) at src/train/main.rs:134
#23 0x00005555556f1499 in train::main::main::{{closure}}::{{closure}} () at src/train/main.rs:61
#24 blocking::unblock::{{closure}}::{{closure}} () at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/blocking-1.0.0/src/lib.rs:303
#25 <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=0x7fffa837d6b0)
    at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
#26 blocking::Executor::spawn::{{closure}} () at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/blocking-1.0.0/src/lib.rs:187
#27 <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=0x7fffa837d6b0)
    at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
#28 0x00005555558deff4 in blocking::Runnable::run (self=...) at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/blocking-1.0.0/src/lib.rs:133
#29 0x00005555558df226 in blocking::Executor::main_loop::{{closure}} () at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/blocking-1.0.0/src/lib.rs:215
#30 std::panicking::try::do_call (data=<optimized out>) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
#31 std::panicking::try (f=...) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
#32 std::panic::catch_unwind (f=...) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
#33 blocking::Executor::main_loop (self=0x555555b40050 <blocking::EXECUTOR+8>) at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/blocking-1.0.0/src/lib.rs:215
#34 0x00005555558dfa36 in blocking::Executor::grow_pool::{{closure}} () at /home/centos/.cargo/registry/src/github.com-1ecc6299db9ec823/blocking-1.0.0/src/lib.rs:267
#35 std::sys_common::backtrace::__rust_begin_short_backtrace (f=...)
    at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
#36 0x00005555558e044a in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} ()
    at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:465
#37 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once (self=..., _args=<optimized out>)
    at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
#38 std::panicking::try::do_call (data=<optimized out>) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
#39 std::panicking::try (f=...) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
#40 std::panic::catch_unwind (f=...) at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
#41 std::thread::Builder::spawn_unchecked::{{closure}} () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:464
#42 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /home/centos/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
#43 0x0000555555939f7a in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/fc2daaae610b5515438b551a2f3706196a997f35/library/alloc/src/boxed.rs:1042
#44 <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/fc2daaae610b5515438b551a2f3706196a997f35/library/alloc/src/boxed.rs:1042
#45 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:87
#46 0x00007fffab956ea5 in start_thread (arg=0x7fffa8384700) at pthread_create.c:307
#47 0x00007fffabf6b8dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by jerry73204** [comment]
It was solved by restricting the GPU usage via reducing the batch size. It might ve related to power issues.
Not sure whether it stems from tch, so I'm closing this issue..
