### ISSUE TITLE
JIT not working with `torchvision.transforms.CenterCrop`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [LaurentMazare/tch-rs#431]
[All files here (`model.pth`, `model.zip`, `main.rs` and `test.py`)](https://drive.google.com/drive/folders/1XyEGzQSQzEu5ED78adkS3rW9UsQUhBZe?usp=sharing)

I have a semantic segmentation model which utilizes a center crop on its output, like:
```python
class UNet(nn.Module):
    def __init__(
        # ...
    ):
        # ...
        self.crop = torchvision.transforms.CenterCrop(output_size)
    def forward(self,x):
        # ...
        crop = self.crop(x)
        # ...
```
Trying to save this as a JIT model results in the error:
```
Traceback (most recent call last):
  File "test.py", line 110, in <module>
    main()
  File "test.py", line 103, in main
    net_trace = torch.jit.trace(model,example_input) # Traces using this batch
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 741, in trace
    return trace_module(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/jit/_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1090, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "test.py", line 84, in forward
    crop = torchvision.transforms.functional.center_crop(final,self.output_size)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 534, in center_crop
    crop_top = int(round((image_height - crop_height) / 2.))
TypeError: type Tensor doesn't define __round__ method
```
If I replace `self.crop = torchvision.transforms.CenterCrop(output_size)` with `self.crop = torch.jit.script(torch.nn.Sequential(torchvision.transforms.CenterCrop(output_size)))` saving with JIT works. However when I then try and run the model from Rust:
```rust
fn main() {
    println!("Hello, world!");
    let model: tch::jit::CModule = tch::CModule::load_on_device("./model.zip", tch::Device::Cpu).unwrap();
    let input = tch::Tensor::ones(&[12,3,300,600],(tch::Kind::Float,tch::Device::Cpu));
    let _ = model
        .forward_ts(&[input])
        .unwrap();
}
```
I get the error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("\nUnknown builtin op: aten::reflection_pad3d.\nHere are some suggestions: \n\taten::reflection_pad1d\n\taten::reflection_pad2d\n\nThe original call is:\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/torch/nn/functional.py\", line 4199\n        elif len(pad) == 6 and (input.dim() == 4 or input.dim() == 5):\n            if mode == \"reflect\":\n                return torch._C._nn.reflection_pad3d(input, pad)\n                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n            elif mode == \"replicate\":\n                return torch._C._nn.replication_pad3d(input, pad)\nSerialized   File \"code/__torch__/torch/nn/functional.py\", line 93\n        if _27:\n          if torch.eq(mode, \"reflect\"):\n            _32 = torch.reflection_pad3d(input, pad)\n                  ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n            _31 = _32\n          else:\n\'_pad\' is being compiled since it was called from \'pad\'\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/transforms/functional_tensor.py\", line 475\n        img = img.to(torch.float32)\n\n    img = torch_pad(img, p, mode=padding_mode, value=float(fill))\n          ~~~~~~~~~ <--- HERE\n\n    if need_squeeze:\nSerialized   File \"code/__torch__/torchvision/transforms/functional_tensor.py\", line 79\n    else:\n      img1, need_cast = img0, False\n    img2 = __torch__.torch.nn.functional._pad(img1, p, padding_mode1, float(fill0), )\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n    if need_squeeze:\n      img3 = torch.squeeze(img2, 0)\n\'pad\' is being compiled since it was called from \'pad\'\nSerialized   File \"code/__torch__/torchvision/transforms/functional.py\", line 76\n    fill: int=0,\n    padding_mode: str=\"constant\") -> Tensor:\n  _26 = __torch__.torchvision.transforms.functional_tensor.pad\n  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  img3 = unchecked_cast(Tensor, img)\n  _27 = _26(img3, padding, fill, padding_mode, )\n\'pad\' is being compiled since it was called from \'center_crop\'\nSerialized   File \"code/__torch__/torchvision/transforms/functional.py\", line 4\n    output_size: List[int]) -> Tensor:\n  _0 = __torch__.torchvision.transforms.functional.get_image_size\n  _1 = __torch__.torchvision.transforms.functional.pad\n  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n  _2 = __torch__.torchvision.transforms.functional.crop\n  _3 = uninitialized(Tensor)\n\'center_crop\' is being compiled since it was called from \'CenterCrop.forward\'\nSerialized   File \"code/__torch__/torchvision/transforms/transforms.py\", line 9\n  def forward(self: __torch__.torchvision.transforms.transforms.CenterCrop,\n    img: Tensor) -> Tensor:\n    _0 = __torch__.torchvision.transforms.functional.center_crop\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\n    size = self.size\n    return _0(img, size, )\n")', src/main.rs:3:98
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The python full file:
```python
import torch
import torch.nn as nn
from torch.nn.modules.batchnorm import BatchNorm2d
import torchvision

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(DoubleConv,self).__init__()
        self.conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )
    def forward(self,x):
        return self.conv(x)

class UNet(nn.Module):
    def __init__(
        self,
        out_channels, # A channel for each label, plus 1 for background
        output_size,
        in_channels = 3,
        features = [64,128,256,512],
    ):
        super(UNet,self).__init__()
        self.ups = nn.ModuleList() # Up sampling layers
        self.downs = nn.ModuleList() # Down sampling layers
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # Down part of UNet
        for feature in features:
            self.downs.append(DoubleConv(in_channels,feature))
            in_channels = feature

        # Up part of UNet
        for feature in reversed(features):
            self.ups.append(nn.ConvTranspose2d(
                in_channels=feature*2,
                out_channels=feature, 
                kernel_size=2, 
                stride=2
            ))
            self.ups.append(DoubleConv(in_channels=feature*2, out_channels=feature))
        
        self.bottleneck = DoubleConv(features[-1], features[-1]*2)
        self.final_cov = nn.Conv2d(features[0], out_channels, kernel_size=1)
        self.output_size = output_size
        self.crop = torchvision.transforms.CenterCrop(output_size)
        # self.crop = torch.jit.script(torch.nn.Sequential(torchvision.transforms.CenterCrop(output_size)))
    
    def forward(self,x):
        skip_connections = []
        # Runs downsampling
        for down in self.downs:
            x = down(x)
            skip_connections.append(x)
            x = self.pool(x)
        # Runs bottleneck
        x = self.bottleneck(x)
        skip_connections = skip_connections[::-1] # Reverse `skip_connections`
        # Runs upsampling
        for index in range(0,len(self.ups),2):
            x = self.ups[index](x)
            # Integer division to map [0,2,4,6,...]->[0,1,2,3,...].
            skip_connection = skip_connections[index//2] 
            # If upscale size does not match saved size, we resize x to match (this should only scale the image by a pixel or two)
            x = torchvision.transforms.functional.resize(x,size=skip_connection.shape[2:])
            # Concates `skip_connection` along channel dimension.
            concat_skip = torch.cat((skip_connection,x),dim=1) 
            
            x = self.ups[index+1](concat_skip)
        final = self.final_cov(x)

        # Crops to center (croping out padding used for context)
        crop = self.crop(final)
        # crop = torchvision.transforms.functional.center_crop(final,self.output_size)

        # Through channels dimension
        softmax = nn.functional.softmax(input = crop, dim = 1) 
        return softmax

STRIDE = [150,300] # Height, Width
WINDOW = [300,600] # Height, Width

def main():
    model = UNet(out_channels=92, output_size=STRIDE)
    print("constructed model")
    
    model.load_state_dict(torch.load(f"model.pth"))
    model.eval()
    print("loaded model")

    # Saves jit model (which can be used in Rust)
    example_input = torch.zeros((1,3,WINDOW[0],WINDOW[1])).type(torch.float32)
    net_trace = torch.jit.trace(model,example_input) # Traces using this batch
    print("traced model")

    torch.jit.save(net_trace,f"model.zip") # TODO Does this need to be `.zip`?
    print("saved model")

if __name__ == "__main__":
    main()
```

**Comment by JonathanWoollett-Light** [comment]
Given a little more investigation this issue seems to relate to PyTorch and not this interface.
