### ISSUE TITLE
Torch("forward did not return a tensor")

### ISSUE THREAD

**Issue by yuanzhoulvpi2017** [LaurentMazare/tch-rs#581]
Thank you so much for creating this amazing library

I meet a very import issue for me . But I can not solve by myself.

May I have a question for you, if you have free time. well~

# NLP filed

well. I convert a pytorch model to `.pt` file. but this model output is a `tuple` type of python

### save model to `.pt` file
```python
from transformers import BertModel, BertTokenizer, BertConfig
import torch

enc = BertTokenizer.from_pretrained("bert-base-uncased")

# Tokenizing input text
text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = enc.tokenize(text)

# Masking one of the input tokens
masked_index = 8
tokenized_text[masked_index] = '[MASK]'
indexed_tokens = enc.convert_tokens_to_ids(tokenized_text)
segments_ids = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

# Creating a dummy input
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])
dummy_input = [tokens_tensor, segments_tensors]

model = BertModel.from_pretrained("bert-base-uncased", torchscript=True)

# Creating the trace
traced_model = torch.jit.trace(model, [tokens_tensor, segments_tensors])
torch.jit.save(traced_model, "traced_bert.pt")

```

## test this `.pt` file in python is ok

```python

loaded_model = torch.jit.load("traced_bert.pt")
loaded_model.eval()

all_encoder_layers, pooled_output = loaded_model(*dummy_input)

print(all_encoder_layers.shape)
print(pooled_output.shape)
```

well. May be you have notion that `loaded_model(*dummy_input)` return a `tuple` in python

## then I use this `.pt` in rust

```rust
use tch::jit;
use tch::CModule;
use tch::Tensor;



fn main() {

    let model = jit::CModule::load(
        "./traced_bert.pt",
    )
    .unwrap();

    let attention_mask = Tensor::of_slice2(&[[
        101, 2040, 2001, 3958, 27227, 1029, 102, 3958, 103, 2001, 1037, 13997, 11510, 102,
    ]]);

    let input_ids = Tensor::of_slice2(&[[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]]);

    let result = model.forward_ts(&[attention_mask, input_ids]).unwrap();

    println!("Hello, world!");
}


```

but raise some err:
```bash
warning: `rustinfer` (bin "rustinfer") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/rustinfer`
conda activate devc
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Torch("forward did not return a tensor")', src/main.rs:23:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1098:23
   4: rustinfer::main
             at ./src/main.rs:23:18
   5: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

in a summary, this error is show that `Torch("forward did not return a tensor")`

so. how can I solve this problem. rewrite `forword_ts` method or else?

how use `tuple` of python in rust?

## finally

thanks~

**Comment by yuanzhoulvpi2017** [comment]
thanks~ I had solved it by change model output(just output a Tensor)

**Comment by maxwellflitton** [comment]
@yuanzhoulvpi2017 can you please provide a code update on how you solved this?
