### ISSUE TITLE
cargo run --example reinforcement-learning --features=python a2c FAILS

### ISSUE THREAD

**Issue by zeroexcuses** [LaurentMazare/tch-rs#64]
### cargo run --example reinforcement-learning --features=python pg

```
cargo run --example reinforcement-learning --features=python pg
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/reinforcement-learning pg`
action space: 2
observation space: [4]
epoch: 0   episodes: 242   avg reward per episode: 20.73
epoch: 1   episodes: 202   avg reward per episode: 24.76
epoch: 2   episodes: 202   avg reward per episode: 24.77
epoch: 3   episodes: 181   avg reward per episode: 27.86
epoch: 4   episodes: 163   avg reward per episode: 30.69

```

### cargo run --example reinforcement-learning --features=python a2c

```
cargo run --example reinforcement-learning --features=python a2c
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/reinforcement-learning a2c`
action space: 6
observation space: [1, 1, 84, 84]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "examples/reinforcement-learning/atari_wrappers.py", line 245, in worker
    ob = env.reset()
  File "/home/x/.local/lib/python3.7/site-packages/gym/core.py", line 257, in reset
    observation = self.env.reset(**kwargs)
  File "/home/x/.local/lib/python3.7/site-packages/gym/core.py", line 271, in reset
    return self.env.reset(**kwargs)
  File "/home/x/.local/lib/python3.7/site-packages/gym/core.py", line 258, in reset
    return self.observation(observation)
  File "/home/x/.local/lib/python3.7/site-packages/gym/core.py", line 266, in observation
    raise NotImplementedError
NotImplementedError
```
(This only shows one thread, as I change the 16 to 1).

### it appears to work running directly from Python:

```
cat test.py ; echo "==="; python3 test.py 
import gym


env = gym.make('SpaceInvaders-v0')
env.reset()
actions = env.action_space.n
===
```

Question: what am I doing wrong & how do we fix this?

**Comment by LaurentMazare** [comment]
Thanks for reporting this issue, it seems that this was caused by some recent changes in the openai gym api. I just pushed a fix for this so let me know if it's still broken for you after updating to the github tip.

**Comment by zeroexcuses** [comment]
Thank you for the quick fix.

I can confirm it is now using lots of CPU/RAM and outputting some type of score. :-)

Closing issue as resolved.

```
cargo run  --example reinforcement-learning --features=python a2c
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/reinforcement-learning a2c`
action space: 6
observation space: [16, 1, 84, 84]
500 230 3.3521739130434782
1000 219 3.310502283105023
```
